services:
      redis:
            image: redis:latest
            container_name: redis
      api:
            build:
                  context: .
                  target: builder
            container_name: fastapi-application
            environment:
                  PORT: 8000
            ports:
                  - '8000:8000'
            restart: "no"